name: SRKitPvP
version: 3.0.0
authors: [Rafael Auler]
main: net.helix.pvp.HelixPvP
description: Plugin de kitpvp do SladePvP
depend: [Core, DecentHolograms, PlaceholderAPI, ajLeaderboards]

commands:
   spawn:
     aliases: [lobby]
   skit:
   youtuber:
   evento:
   tpall:
   sc:
   report:
   crash:
   setarena:
   regras:
   req:
   tag:
   money:
   dinheiro:
   aplicar:
   warp:
   set1v1:
   sendtitle:
   givecoins:
   site:
   autosoup:
   pvp:
   euforia:
   macrotest:
   yt:
   grupo:
   setfeast:
   loja:
   raikiri21:
   sudo:
   warpinfo:
   fly:
   kitpvp:
   reporttoggle:
   sealend123:
   lavainiciar:
   arenainiciar:
   membro:
   shutdownserver:
   pinfo:
   givekills:
   givedeaths:
   resetkdr:
   givekit:
   v:
   vanish:
   medalhas:
   medalha:
   consolesudo:
   requisitos:
   discord:
   sethologram:
   rank:
      aliases: [ranks]
   scoreboard:
      aliases: [score]
   verrank:
      aliases: [profile]
   sortearplayer:
      aliases: [sortear]   
   sorteio:
   actionbar:
   
   
   